name:                tylisp
version:             0.1.0.0
github:              "kazark/tylisp"
license:             BSD3
author:              "Keith Pinson"
maintainer:          "kazark@zoho.com"
copyright:           "2022 Keith Pinson"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kazark/tylisp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tylisp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tylisp

tests:
  tylisp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tylisp
