name:                ennalleen
version:             0.0.0.1
github:              "PolyglotSymposium/pyrgos/ennalleen"
license:             MIT
author:              "Keith Pinson"
maintainer:          "kazark@zoho.com"
copyright:           "2020 (c) Keith Pinson"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/PolyglotSymposium/pyrgos/ennalleen#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- mtl

library:
  source-dirs: src

executables:
  ennalleen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ennalleen

tests:
  ennalleen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ennalleen
