name:                metacore
version:             0.1.0.0
github:              "kazark/pyrgos"
license:             MIT
author:              "Keith Pinson"
maintainer:          "kazark@zoho.com"
copyright:           "2019 (c) Keith Pinson"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/metacore#readme>

dependencies:
- MissingH
- base >= 4.7 && < 5
- containers
- megaparsec
- transformers

default-extensions:
- BlockArguments
- LambdaCase

library:
  source-dirs: src

executables:
  metacore-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metacore

tests:
  metacore-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metacore
